--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3 (Debian 13.3-1.pgdg100+1)
-- Dumped by pg_dump version 13.3 (Debian 13.3-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: car_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.car_table (
    car_id integer NOT NULL,
    reg_num character varying NOT NULL,
    mark character varying NOT NULL,
    model character varying NOT NULL,
    year integer NOT NULL,
    owner_name character varying NOT NULL,
    owner_surname character varying NOT NULL,
    owner_patronymic character varying
);


ALTER TABLE public.car_table OWNER TO "user";

--
-- Name: car_table_car_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.car_table ALTER COLUMN car_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_table_car_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: car_table car_tabble_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.car_table
    ADD CONSTRAINT car_tabble_pkey PRIMARY KEY (car_id);


--
-- Name: car_table reg_num_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.car_table
    ADD CONSTRAINT reg_num_uniq UNIQUE (reg_num);


--
-- PostgreSQL database dump complete
--